---
title: 'Midterm 2: Practice Submission'
author: "Student name and ID"
date: "Today's Data"
output: pdf_document
---

**This is an example of what your second midterm will look like. The policies below are likely to be updated on exam day so be sure to read them carefully** \

Please read the following statement and type your name below to indicate that you understand the policies for this exam.\

This is a take home exam. Your turned in exam **must be eight pages in length** with each answer on a separate page. Your work must be **original** and **unique**. You may need to create R chunks to show and run code. Don't forget to display your output when necessary. Additionally, make sure your code/interpretations do not run off the page. **CAREFULLY** look at your PDF once you've submitted to be sure it is exactly the way you want it. It is your responsibility to submit your work.\ 

Unless otherwise specified in the question, express proportions/probabilities as percents and round any calculated answers to 2 decimal places. \

“I understand the University of California policy on academic integrity. I will not collaborate on this exam with my classmates or any other individuals. I understand that if I violate any of these policies, I will receive a 0 on this exam." \

TYPE YOUR NAME HERE:
\


\newpage

## Symbols and Notation 

Here are some commonly used latex math options that you may find useful in answering test questions. To avoid submission issues, please DO NOT copy math symbols from PDF; use the notation that we have provided below. To use these latex math symbols, make sure that the expression begins and ends with a $ (i.e. in rmd, the dollar signs of the expression should turn magenta and the text should be grey - if you have changed your color scheme, these colors could be different); you do not need to include the parentheses in your expression.  

- Greater than or equal to ($\ge$)  \
- Less than or equal to ($\le$) \
- Conditional on ($\mid$)   \
- Union ($\cup$)  \
- Intersection ($\cap$)  \
- Mu ($\mu$)   \
- Sigma ($\sigma$)  \
- Sample mean ($\bar{x}$)  \
- Sample proportion ($\hat{p}$)  \
- Null hypothesis ($H_{0}$)  \
- Alternative hypothesis ($H_{A}$) \

Symbols that DO NOT require you to use latex math options: 

- greater than (>)  \
- less than (<)  \



\newpage

### Question 1: Adapted from Baldi and Moore 3rd edition
The average height for female-identifying individuals aged 18-24 in the United States is 64.5 inches with a known standard deviation of 2.5 inches. You are interested in determining if the heights of female-identifying individuals aged 18-24 at UC Berkeley is different than the national average. You sample 78 students from Berkeley and save them in a dataset called `heights`.

```{r heights-generate, include = F}
set.seed(142)
heights <- rnorm(78, 62, 2.5)
heights <- data.frame(heights)
```


\newpage
**[1 point] Question 1a. Define your null and alternative hypotheses using standard notation.**



\newpage
**[1 point] Question 1b. Calculate and report the test statistic corresponding with this data.**



\newpage
**[2 point] Question 1c. Calculate and report the p-value associated with your statistic. Interpret your p-value in the context of the question. **




\newpage
**[1 point] Question 1d. Is the height of female-identifying students at Berkeley different than the national average? Determine if you reject your null hypothesis or not.**

\newpage
### Submission

For assignments in this class, you'll be submitting using the **Terminal** tab in the pane below. In order for the submission to work properly, make sure that:

1. Any image files you add that are needed to knit the file are in the `src` folder and file paths are specified accordingly. 
2. You **have not changed the file name** of the assignment.
3. The file is saved (the file name in the tab should be **black**, not red with an asterisk).
4. The file knits properly.

Once you have checked these items, you can proceed to submit your assignment.

1. Click on the **Terminal** tab in the pane below.
2. Copy-paste the following line of code into the terminal and press enter.

cd; cd ph142-sp20/labs/mid2-sample; python3 turn_in.py

3. Follow the prompts to enter your Gradescope username and password. When entering your password, you won't see anything come up on the screen--don't worry! This is just for security purposes--just keep typing and hit enter.
4. If the submission is successful, you should see "Submission successful!" appear as output.
5. If the submission fails, try to diagnose the issue using the error messages--if you have problems, post on Piazza. 

The late policy will be strictly enforced, **no matter the reason**, including submission issues, so be sure to submit early enough to have time to diagnose issues if problems arise.
